### PR TITLE
Added refreshAccess function

### PR DESCRIPTION
**Pull request by dougrich**

### CODE REVIEW

**Comment by alaabouayed** [comment]
Hey @dougrich. Thanks for the pull request. 

Just so I'm clear, you've added refreshToken which is a function that links my client id, secret and refresh token values and assigns them to the relevant keys in the payload variable. 

You've then set up a request-promise, within the refreshToken function, which makes a POST call to get a new accessToken. 

I believe I've understood that all correctly. 

I'll likely need to use this function within my routes, so I can make sure I have a valid accessToken to pass into the Calendar API call. I presume that I'll just export the refreshToken function and require it in app.js? I can then maybe use it as middleware, or directly within the route function body?

Have I understood all of that correctly?

**Comment by dougrich** [comment]
Yep. As I said, you pretty much had everything in place, and that would work.

If you go down the middleware route, you'd also want to do a couple more steps.

In pseudocode, the middleware on its own would be:

```js
function withAccessToken(req, res, next) {
  if (!isLoggedIn()) return res.status(401).end('Not Authorized');
  const { access, expiry, refresh } = getUser()
  if (isExpired(access, expiry) {
    const { access, expiry } = refreshAccess(refresh)
    updateUser(access, expiry)
  }
  req.locals.accessToken = access
  next()
}
```

That said: since you've already brought in Passport.js, I'd instead point you to the `deserializeUser` on lines 11-13. Here you could check if your currently saved access token has expired and refresh if needed, and store on the user. That would look like (again in pseudo code):

```js
passport.deserializeUser(function(id, done){
  User.findById(id).then(function(user){
    if (hasExpiredAccess(user)) {
      const { access, expiry } = refreshAccess(user.refresh)
      updateUser(access, expiry)
    }
    done(null, user);
  })
});
```

If you'd like me to update my pull request with one of these two options, let me know. I wasn't sure if you wanted a completed solution, or the building blocks to get past your current hurdle.

**Comment by alaabouayed** [comment]
That's great - thanks for the instructions and explanation. 

The middleware option makes a little bit more sense to me at the moment - so I'll down that route I think. 

I wouldn't want to take up more of your time constructing another pull request so I'll use the helpful building blocks you've written and see where it leads me!

**Comment by dougrich** [comment]
Alright, sounds good - are you planning to merge in this pull request, or do you have what you need?

**Comment by alaabouayed** [comment]
I've copied some of the code into my code on a new branch just to see how it works. Merging code directly into master that I wasn't completely clear on scared me a bit! 

I have a few questions about the code that you wrote. Do you think I could ask you about it - would that be okay?

**Comment by dougrich** [comment]
Yep, go for it - what do you want to know?

**Pull request closed without merging**
